### ISSUE TITLE
Basic Questions

### ISSUE THREAD

**Issue by xmeadow** [szymor/soulfu#1]
Hello there, big fan of soulfu here.
Is this the lates source?
Does is compile on linux?
What are you planning to do?
Is Niceware a real licence?

**Comment by szymor** [comment]
I do not follow SoulFu development anymore, but according to my limited knowledge, this is the latest version of Soulfu released by the original author with patches (not made by me) allowing to compile it using unmodified external libraries - I do not remember which ones, but it is not important. Additionally, I applied patches to support 16:9 screens - without them you would see black stripes at sides of the screen during gameplay. I know newer versions of SoulFu created by fans exist somewhere in the Internet, but I consider them unstable and decided not to preserve them.
The game compiles with no issues on 32 bit Linux or on 64 bit Linux in 32 bit compatibility mode. I have tested it on a x86/x64 platform. I have no idea about ARM and ARM64 support but I assume it should work correctly for ARM and would crash for ARM64, mainly due to platform-specific nature of SDF archive format. I do not plan to make it working on 64 bit platforms.
In general, I do not plan to develop the game. I had such plans in the past, though. One of them was to port it to RG350 and RG351 handheld consoles, but I lack both time and the game consoles to work on it. The game also needs heavy refactoring, much code is written in very platform-specific manner which makes it hard to port to other platforms.
Niceware is a real licence which was applied by the original author of the game. Unfortunately, it is not GNU GPL compatible, which could cause the community to lose interest in the project.

**Comment by xmeadow** [comment]
Thanks for this quick answer!
That is what I thought. SoulFu seems really quite dead- but it use to be a really nice game and could have had a nice future. But i somehow had this fear that you shouldn't remove the niceware-thing. Without permission of Aaron Bishop himself. Would be great if he just drops by and relicense it to something less annoying.
My RG350M lies next to me and I really didn't think about this possibility 😄 If you start any attempts to port it I would be glad to help / test. Until then, I will try to get it running on Haiku-OS.

**Comment by szymor** [comment]
I have a bad feeling about Aaron. I could not find any Internet activity of his for the last couple of years.
Speaking of porting, I am afraid that the game would look awful in 320x240, especially fonts are barely readable. Some consoles have higher resolution so maybe it would look better on them. If I were to start working on it, one of the first things I would do would be:
1) generation of SDF from resource files (using internal DEVTOOL is problematic, tracking changes in source code is impossible while storing SDF in binary format),
2) making the game platform-agnostic (support for both 32 and 64 bits for every popular architecture),
3) modularization (currently module .c files are being included by one main .c file, which is not a good practice, though it surely helps with code optimization - it still gives better results than using LTO),
4) removal of big macros, using functions instead,
5) using commonly known solutions instead of reinventing the wheel (e.g. Lua instead of custom script system).
If things above are not done, I do not see bright future of this project as it is a nightmare to manage it as it is now.

There are some GNU GPL notes inside of source code. They were not made by me and I consider them misleading and false information, but I do not care enough to change it.

I wish you all the best with porting it to HaikuOS. I encourage you to share your work with public.

**Comment by szymor** [comment]
@xmeadow I guess you may be interested in the latest development.

Ad. 1. Done, refer to soulfu-data-packer repo.
Ad. 2. To be done - a new SDF format needs to be reinvented but it is quite possible to do so.
Ad. 3. Dropped, it is not as bad as I thought before, though it is spaghetti code :) It can be improved over time anyway.
Ad. 4. Dropped.
Ad. 5. To be done in the future, not a priority for now.

Besides above, a language file converter has been implemented - just a tiny tool to make easier to edit language files. That's right, with some effort it would be possible to have multilingual support.

What is being done now?
1. Packing and unpacking SDF is only a beginning. In order to properly play a game, some resources need to be prepared, e.g. scripts need to be compiled. At the moment I am working on a standalone script compiler.
2. 3D models could be prepared using external tools. The issue needs to be investigated and proper converters implemented. The same thing is with music files.
3. In the nearest future I also plan to integrate some of fan modifications, e.g. save system or arena, into the source code.
4. And fix aspect ratio of my 16:9 mod.
5. Maybe some other minor modifications extending functionality of the game.
6. Maybe aforementioned 64-bit and multilingual support?
7. Maybe port for OpenDingux? The topic needs to be investigated.

In general, the plan is to create the tools enabling sharing artifacts between developer, which, I believe, was a reason behind low popularity of the game among modders and developers. I do not plan to push feature development too much on my own.

**Comment by szymor** [comment]
I close this thread as I write down the progress in README.
