### ISSUE TITLE
Could you list the compilation requiements?

### ISSUE THREAD

**Issue by justinmcgrath** [szymor/soulfu#2]
On Linux, I assume it's using gcc and make. On Windows is it the original mingw from here, https://sourceforge.net/projects/mingw/, or the one included with MSYS2?

**Comment by szymor** [comment]
MINGW32-MSYS2. I believe it is a 32 bit version of mingw-w64 but I am not sure. However, the experimental release was cross-compiled for Windows on Linux.

The game cannot be compiled in 64 bit mode because it relies heavily on 4-byte pointers.

On Windows you can expect multiple build issues as it is not a primary environment for me. Examples include:
- halting during SDF archive generation (unknown reason),
- script compilation errors for CRLF line endings (this is expected).
Clone the repository without EOL conversion if possible.

If you encounter issues with creating SDF, you can take it from the last release.

Sorry for inconvenience.

**Comment by hhyyrylainen** [comment]
For me on Fedora 39 I installed the following: `sudo dnf install sdl12-compat-devel.i686 SDL_net-devel.i686 glibc-devel.i686`. That got the compilation process to start, but linking fails completely with a ton of undefined references:
```
$ make
Package SDL_net was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL_net.pc'
to the PKG_CONFIG_PATH environment variable
Package 'SDL_net', required by 'virtual:world', not found
Package 'sdl', required by 'virtual:world', not found
cc -m32 -DDEVTOOL -o soulfu -Isource source/soulfu.c -lm 
/usr/bin/ld: /tmp/cceW7i9M.o: in function `timer_start':
soulfu.c:(.text+0x2bd): undefined reference to `SDL_GetTicks'
/usr/bin/ld: /tmp/cceW7i9M.o: in function `timer_end':
soulfu.c:(.text+0x2d0): undefined reference to `SDL_GetTicks'
/usr/bin/ld: /tmp/cceW7i9M.o: in function `main_timer_start':
soulfu.c:(.text+0x30c): undefined reference to `SDL_GetTicks'
/usr/bin/ld: /tmp/cceW7i9M.o: in function `main_timer_end':
soulfu.c:(.text+0x31f): undefined reference to `SDL_GetTicks'
/usr/bin/ld: /tmp/cceW7i9M.o: in function `decode_jpg':
soulfu.c:(.text+0x5d82): undefined reference to `jpeg_std_error'
```

**Comment by szymor** [comment]
Good to hear it works for you now. I have not tested the game on multiple monitors, but it would be surely a nice feature to have implemented.

Unfortunately, due to personal reasons, I am unable to do any long-term development :( Proper build system, polished translation for many languages and support for multiple monitors would be high on my priority list if I continued working on the project.

**Comment by szymor** [comment]
I have uploaded a package containing SoulFu to AUR, so if you are an Arch Linux user, you should be able to utilize the power of your package manager to install the game.

The link: https://aur.archlinux.org/packages/soulfu-git

Users of other distros can use it to check required dependencies if in doubt.

**Comment by szymor** [comment]
I consider the issue resolved. If in need, please create a new issue.
