### ISSUE TITLE
Respect thread

### ISSUE THREAD

**Issue by szystem** [szymor/soulfu#8]
I just wanted to express my uttermost respect for bringing this game back. 
A question and suggestion: I remember going all the way down to the Abyss with my brother and OP elf, but nothing was really there.
Have you been thinkin about adding some sort of a final boss or the game outro, assuming we haven't missed anything?
Cheers!

**Comment by szymor** [comment]
I do not plan to add any major content to the game, mostly because of lack of my skills and limited free time. Aaron wanted to add more stuff like beholders or ogres, but he abandoned the project.

If a proper artist with basic computer knowledge joined the team, you could expect more stuff to be created. Aaron left ideas and assets for abyss and elven forest, so it would be one of first things to be developed.

Personally, I would like to finish Polish translation, move the code base to 64 bits and port it to SDL2. The last two are mundane features from the player's perspective, but in the long run they are needed to keep the game alive (at least from technical perspective). Other important goals include creating a proper build system, maybe even CI/CD, to be able to release the game effortlessly for multiple platforms at once, but it is far from being started.

More minor stuff awaits to be done, though, like AI, new items, rebalancing gameplay or even new rooms, but I rather consider them a way to entertain myself, not things that need to be done. Maybe I should finish Annigal doll quest?

BTW, I never reached the abyss :) I plan to do it while testing new features being developed.
